name: CI n8n

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract release version
        id: meta
        run: echo "release_version=0.1.0-test" >> "$GITHUB_OUTPUT"

      - name: Gate: artifact completeness
        env:
          N8N_URL: ${{ secrets.N8N_URL }}
        run: |
          curl -sS -X POST "$N8N_URL" \
            -H "Content-Type: application/json" \
            -d @- <<'EOF'
          {
            "release_version": "${{ steps.meta.outputs.release_version }}",
            "commit_sha": "${{ github.sha }}"
          }
          EOF
